---
ENV_DATA:
  bin_dir: "/usr/local/bin"
  noobaa_core_dir: "/usr/local/noobaa-core"
  noobaa_conf_dir: "/etc/noobaa.conf.d"
  node_cmd: "node"
  nsfs_env: "/usr/local/noobaa-core/nsfs_env.env"
  package_json: "/usr/local/noobaa-core/package.json"
  storage_dir: "/usr/local/noobaa-core/storage"
  postgresql_dir: "/var/run/postgresql"
  env_file: "/usr/local/noobaa-core/.env"
  config_local: "/usr/local/noobaa-core/config-local.js"
DEPLOYMENT:
  backing_stores: 4
  backing_store_drive_path: "/usr/local/noobaa-core/storage/backingstores"
  backing_store_drive_prefix: "drive"
  backing_store_drive_port: 9990
  upstream_rpm_s3_base_url: "https://noobaa-core-rpms.s3.amazonaws.com"
  upstream: false  # Update to true if you want automatic upstream rpm find
  rpm_rhel_version: 9
  rpm_arch: "x86_64"
  rpm_pattern: "noobaa-core-.*\\.el{rhel_version}\\.{arch}\\.rpm"
  downstream_rpm_base_url: "https://na.artifactory.swg-devops.com"
  downstream_rpm_artifactory_path:  'artifactory/sys-ceph-team-rpm-local/unsigned/'
  # rpm_auth_username: username required for download RPM
  # rpm_auth_password: password required for download RPM
